# Use an official Node.js runtime as the base image
FROM node:17-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json .
COPY ./package-lock.json .

# Install app dependencies
RUN npm install

# Copy the rest of the app source code to the container
COPY . .



# Expose the port your app runs on (e.g., 3000)
EXPOSE 3000

# Define the command to serve the built app
CMD ["npm", "run", "dev"]